# INTRODUCTION

* NUMPY STANDS FOR Numerical Python
* Developed in 2005 by Travis Oliphant
* Lingua Franca for data exchange
* nd array-a  n-dimensional array 
* Fast operations on entire arrays
* Reading / writing array data 
* Linear Algebra operations 

## Why numpy ?


* Numpy internally stores data in a contiguous block of memory
* Complex computations on entire arrays

# Numpy vs Python List

In [1]:
L=range(1000000)

In [2]:
import numpy as np

In [3]:
d=np.arange(1000000)

In [8]:
%time for i in range (1,10): r=[x*2 for x in L] #execution time for list multiplies by 2 in 10 iteration

Wall time: 2.74 s


In [7]:
%time for i in range(1,10): r=[d*2] #execution time for numpy array multiplies by 2 in 10 iteration

Wall time: 57.8 ms


Hence numpy is much faster than python

# A multidimensional Array Object

### nd array()

* A fast,flexible container for large datasets in python
* Homogeneous data i.e all of the element must be the same type

In [9]:
import numpy as np

In [10]:
x=np.zeros((4,4))

In [11]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.empty((2,2)) #empty function returns random number from memory but in required shape

array([[1.17882268e-311, 9.42965228e-247],
       [2.13862630e+161, 2.53938807e+151]])

In [16]:
L=[1,2,3,4,5]

In [20]:
c=np.array(L) #List is converted into numpy array

In [21]:
c

array([1, 2, 3, 4, 5])

In [24]:
x=np.arange(0,100,10)

In [25]:
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
x.shape #shape of an array is 10

(10,)

In [27]:
x=np.zeros((10,10))

In [28]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
x.shape #shape of an array is 10,10

(10, 10)

In [30]:
y=x.reshape((2,2,5,5)) #you can reshape the array but must fulfil the origional shape

In [31]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [32]:
y.dtype #you can check the type of an array

dtype('float64')

In [33]:
y.ndim #you can also check its dimension 

4

In [34]:
x.ndim #you can also check its dimension 

2

# Arithmetic with ndarray

### Vectorizatrion

* Express batch operations on data without writing any for loops
* Any arithmetic operations between equal-size arrays applies the operation element-wise
* Arithmetic operations with scalars propagate the scalar argument to each element in the array

In [35]:
import numpy as np

In [36]:
a=np.random.randn((10)) #we generated random number

In [37]:
b=np.random.randn((10)) #we generated random number

In [38]:
a

array([ 0.22245496,  0.11684342, -0.66419938, -0.78240585, -0.95917359,
        0.27412314,  1.11499032, -0.16052685,  0.7058117 ,  0.3725994 ])

In [39]:
b

array([-0.5363705 ,  0.4695086 , -1.15836067,  0.22142532, -1.28181326,
        0.41613583,  0.28399631,  2.57661198, -0.73528012, -1.03984469])

Now we perform aritmetic operations in a and b

In [40]:
a+b

array([-0.31391554,  0.58635202, -1.82256004, -0.56098053, -2.24098685,
        0.69025896,  1.39898663,  2.41608513, -0.02946842, -0.66724529])

In [41]:
a-b

array([ 0.75882547, -0.35266517,  0.49416129, -1.00383117,  0.32263967,
       -0.14201269,  0.83099401, -2.73713883,  1.44109182,  1.41244409])

In [42]:
a*b

array([-0.11931828,  0.05485899,  0.76938243, -0.17324447,  1.22948142,
        0.11407246,  0.31665314, -0.41361541, -0.51896931, -0.38744551])

In [43]:
2*a

array([ 0.44490993,  0.23368685, -1.32839875, -1.5648117 , -1.91834718,
        0.54824627,  2.22998064, -0.3210537 ,  1.4116234 ,  0.7451988 ])

In [44]:
1/a

array([ 4.49529193,  8.55846198, -1.50557203, -1.27810906, -1.04256415,
        3.64799562,  0.89686877, -6.22948744,  1.41680847,  2.68384758])

In [45]:
a>0

array([ True,  True, False, False, False,  True,  True, False,  True,
        True])

In [46]:
a[a>0] #This function returns true values

array([0.22245496, 0.11684342, 0.27412314, 1.11499032, 0.7058117 ,
       0.3725994 ])

Similarly

In [69]:
x=np.ones((5,5))

In [70]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
y=np.zeros((5,5))

In [72]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
x+y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
x-y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
x*y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
1/x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
1/y

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [82]:
x>y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [83]:
y>x

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [84]:
x[x>y]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

# Indexing & Slicing 

### Indexing

* Act similar to Python List
* Boolean indexing: Specifying boolean arrays as index
* Fancy indexing: Specifying arbitrary arrays as indexes

### Slicing

* Array slices are views on the origional array
* Format -start:end:step

In [85]:
import numpy as np

In [86]:
x=np.array([1,7,9,8,5])

In [87]:
x[4] #indexing

5

In [88]:
x[x>5] #returns the values which are greater than 5

array([7, 9, 8])

In [89]:
x[[2,1]] #Fancy indexing

array([9, 7])

In [90]:
x=np.random.randn(10,10)

In [91]:
x

array([[-1.69385388, -0.45061403, -1.07043136, -0.14067004, -0.3683454 ,
         1.61343416,  1.1009701 , -0.3305501 , -0.99893921, -0.10549903],
       [-0.10353701, -0.51295633, -1.23969542, -1.16228281, -1.82796026,
        -0.2686334 , -0.02979802, -0.51083648,  0.22243277, -0.79285818],
       [-0.72410585,  0.64299828, -0.8173602 , -0.05177215, -0.68375886,
        -0.87495763, -0.00713886, -0.30280046,  0.05452398,  1.28005842],
       [-1.53941208, -0.52043238,  0.33834052, -1.16753112,  2.36727001,
        -0.06122408,  1.41931348, -0.54113461, -0.14966845, -0.18438069],
       [ 0.59756832, -0.12153477,  0.27714671, -0.07404164,  0.53583572,
        -0.56531821,  0.84026447,  0.37734027, -1.33065012,  0.24097639],
       [ 1.07265599,  1.89708557,  0.6345552 ,  0.52284822,  0.10743509,
        -1.17759542,  1.27001223,  1.48429183, -0.00342436,  0.42744052],
       [-1.58394427,  0.77665307,  0.67204767, -0.51396238,  1.04022368,
        -0.36729932, -1.0089854 , -0.83536387

In [92]:
x[0]

array([-1.69385388, -0.45061403, -1.07043136, -0.14067004, -0.3683454 ,
        1.61343416,  1.1009701 , -0.3305501 , -0.99893921, -0.10549903])

In [93]:
x[0][4] #we extract the fourth value from 0 positional array

-0.3683453986482173

In [94]:
x[1:10:2,::] #slicing for odd rows

array([[-0.10353701, -0.51295633, -1.23969542, -1.16228281, -1.82796026,
        -0.2686334 , -0.02979802, -0.51083648,  0.22243277, -0.79285818],
       [-1.53941208, -0.52043238,  0.33834052, -1.16753112,  2.36727001,
        -0.06122408,  1.41931348, -0.54113461, -0.14966845, -0.18438069],
       [ 1.07265599,  1.89708557,  0.6345552 ,  0.52284822,  0.10743509,
        -1.17759542,  1.27001223,  1.48429183, -0.00342436,  0.42744052],
       [ 0.75501459,  1.48294402,  1.1724163 , -1.6017417 ,  0.17146917,
        -0.32105835, -0.2555927 , -1.01821868,  0.4808158 ,  1.34703024],
       [ 2.57271741, -0.78921483, -1.33881988,  0.82464621, -1.53197988,
         0.82681105,  0.22811569,  1.02352892, -0.43207186,  1.66956019]])

In [95]:
#or 
x[1:10:2]

array([[-0.10353701, -0.51295633, -1.23969542, -1.16228281, -1.82796026,
        -0.2686334 , -0.02979802, -0.51083648,  0.22243277, -0.79285818],
       [-1.53941208, -0.52043238,  0.33834052, -1.16753112,  2.36727001,
        -0.06122408,  1.41931348, -0.54113461, -0.14966845, -0.18438069],
       [ 1.07265599,  1.89708557,  0.6345552 ,  0.52284822,  0.10743509,
        -1.17759542,  1.27001223,  1.48429183, -0.00342436,  0.42744052],
       [ 0.75501459,  1.48294402,  1.1724163 , -1.6017417 ,  0.17146917,
        -0.32105835, -0.2555927 , -1.01821868,  0.4808158 ,  1.34703024],
       [ 2.57271741, -0.78921483, -1.33881988,  0.82464621, -1.53197988,
         0.82681105,  0.22811569,  1.02352892, -0.43207186,  1.66956019]])

In [96]:
x[::,0:4] #all rows & only 4 columns

array([[-1.69385388, -0.45061403, -1.07043136, -0.14067004],
       [-0.10353701, -0.51295633, -1.23969542, -1.16228281],
       [-0.72410585,  0.64299828, -0.8173602 , -0.05177215],
       [-1.53941208, -0.52043238,  0.33834052, -1.16753112],
       [ 0.59756832, -0.12153477,  0.27714671, -0.07404164],
       [ 1.07265599,  1.89708557,  0.6345552 ,  0.52284822],
       [-1.58394427,  0.77665307,  0.67204767, -0.51396238],
       [ 0.75501459,  1.48294402,  1.1724163 , -1.6017417 ],
       [-0.83162001, -0.30933288,  0.38855927,  1.50058108],
       [ 2.57271741, -0.78921483, -1.33881988,  0.82464621]])

In [97]:
x=np.ones((5,5))

In [98]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
x[1:-1,1:-1]=0

In [102]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
y=np.zeros((5,5))

In [141]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [144]:
y[0:5:2]=0

In [145]:
y

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [146]:
z=np.ones((5,5))

In [147]:
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [148]:
 z[::,0:24:2]=0

In [149]:
z

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

# Fast Element-Wise Array Function

### Element-wise array function

* sqrt
* maximum
* abs,fabs
* square
* exp
* log,log10
* log2,log1p
* sign
* ceil
* floor
* rint
* modf
* isnan
* is finite,is inf
* cos,cosh,sin,sinh,tan,tanh
* arccos,arccosh,arcsin,arcsinh,arctan,arctanh

In [150]:
import numpy as np

In [151]:
x=np.array([10,9,8,7,6,11])

In [153]:
np.sqrt(x) #return square or array

array([3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974,
       3.31662479])

In [154]:
np.power(x,2)

array([100,  81,  64,  49,  36, 121], dtype=int32)

In [163]:
y=[7,1,2,3,-1,2]

In [164]:
z=np.maximum(x,y)

In [165]:
z

array([10,  9,  8,  7,  6, 11])

# NP.Where Function

### np.where()

* A vectorized version of the ternary expression x if condition else y


In [166]:
import numpy as np

In [169]:
x=np.array([0,-1,10000,50000])

In [170]:
x

array([    0,    -1, 10000, 50000])

In [178]:
np.where(x<=0,25000,x) # it is similar to python if else condition look if x is less than or equal to 0 put there 25000
                       # or else put their origional x value

array([25000, 25000, 10000, 50000])

In [179]:
np.where(x<=0,"no.is less than 0","no. is greater than 0 so will not change value of array")

array(['no.is less than 0', 'no.is less than 0',
       'no. is greater than 0 so will not change value of array',
       'no. is greater than 0 so will not change value of array'],
      dtype='<U55')

In [180]:
x

array([    0,    -1, 10000, 50000])

# Mathematical & Statistical Methods

### Mathematical & Statistical Methods

* mean(): returns the mean value computed over the array
* cumsum(): returns the cumulative sum of array elements
* cumprod(): returns the cumulative product of array elements

### Methods for Boolean Arrays

* sum(): counting True values in a boolean array
* any():tests whether one or more values in an array is True
* all():checks if energy value is True


### Some other function

* Sorting
* Unique

In [181]:
import numpy as np

In [182]:
x=np.array([10,9,7,10,7])

In [183]:
x.mean()

8.6

In [184]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [185]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [186]:
y=x>6

In [187]:
y

array([ True,  True,  True,  True,  True])

In [188]:
y.sum()

5

In [189]:
y.any()

True

In [190]:
y.all()

True

In [191]:
y=x>7

In [192]:
y

array([ True,  True, False,  True, False])

In [193]:
y.sum()

3

In [194]:
y

array([ True,  True, False,  True, False])

In [195]:
y.any()

True

In [196]:
y.all()

False

In [197]:
x.sort()

In [198]:
x

array([ 7,  7,  9, 10, 10])

In [199]:
np.unique(x)

array([ 7,  9, 10])

# File Input & Output

* np.save(filename.npy,array)
* np.load(filename.npy)
* np.savez(filename.npz,array1,arra2)
* when loading an.npz file,you get back a dict-like object

In [200]:
import numpy as np

In [201]:
x=[1,4,5,7]

In [202]:
y=[8,7,9]

In [203]:
np.save("testx",x)

In [204]:
loadx=np.load("testx.npy")

In [205]:
loadx

array([1, 4, 5, 7])

In [206]:
np.savez("testxy",x,y)

In [207]:
loadxy=np.load("testxy.npz")

In [208]:
loadxy

# Linear Algebra Function

* diag
* dot
* trace
* det
* eig
* inv
* pinv
* qr
* svd
* solve
* lstsq

In [209]:
import numpy as np

In [210]:
x=np.random.randn(3,2)

In [211]:
y=np.random.randn(2,3)

In [212]:
x.dot(y) #dot product of x & y

array([[-0.45983835,  1.94044515,  0.28872183],
       [-0.17455543,  0.76095806, -1.71425181],
       [-0.03883995,  0.1772701 , -0.97668742]])

In [213]:
x.transpose()

array([[ 0.27885466, -0.79061915, -0.46850211],
       [ 2.05128012,  0.29128112, -0.09425733]])

In [214]:
x.trace()

0.5701357733328369

# Pseudo Random Number

### distributions:

* normal()
* seed()
* gamma()
* uniform()

In [215]:
import numpy as np

In [216]:
np.random.seed(7)

In [217]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [218]:
np.random.uniform(size=(3,4))

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992]])

#  Reshape

* C order: Row major order
* Fortran order: column major order
* Specifying -1 for reshape() means the value used for that dimension will be inferred from the data
* ravel() or flatten () i.e flattening to one dimension

In [219]:
import numpy as np

In [220]:
x=np.random.randn(4,5)

In [221]:
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [222]:
x.reshape((2,2,5))

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [223]:
x.reshape((2,2,5), order="F")

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936]],

       [[-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [224]:
x.reshape((2,2,5), order="C")

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [225]:
x #x is not save we have to save it before

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [226]:
x.ravel()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

In [227]:
x.flatten()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

# Concatenates

* Takes a sequence of (tuple,list,etc) of arrays and joins them together in order along the input axis

In [228]:
import numpy as np

In [229]:
x=[[1,3,5],[7,9,0]]

In [230]:
arr1=np.array(x)

In [231]:
y=[[11,13,15],[17,19,10]]

In [232]:
arr2=np.array(y)

In [233]:
np.concatenate((arr1,arr2),axis=0) #setting axis = 0 concatenates along the row axis

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [234]:
np.concatenate((arr1,arr2),axis=1) #setting axis = 1 concatenates along the column axis 

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [235]:
np.vstack((arr1,arr2)) #vstack : stack arrays row-wise (along axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [236]:
np.hstack((arr1,arr2)) #hstac : stack arrays column-wise (along axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

# Numpy Splits

* Split slices apart an array into multiple arrays along an axis

In [237]:
import numpy as np

In [238]:
x=[1,4,5,6,7,9,1,4]

In [239]:
d=np.array(x)

In [245]:
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [246]:
x=[[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]]

In [247]:
d=np.array(x)

In [250]:
np.split(d,[4,6], axis=1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  9],
        [17, 19]]), array([[ 1,  4],
        [11, 14]])]

In [251]:
np.split(d,[1],axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

# Tile & Repeat

### Repeat():

* repeat replicates each element in an array some number of times,producing a larger array
* if you pass an array of integers,each element can be repeated a different number of times
* np.repeat(): Repeat every item of an input,and puts the repeated number into a new array


### Tile():

* Tile is a shortcut for stacking copies of an array along an axis

In [252]:
import numpy as np

In [253]:
d=np.array([1,5,7,8])

In [254]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [255]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

# Conclusion

* Covered ndarray: creating indexing, slicing, I/O, Liner Algebra, Random Number generation.
* Advanced concepts such as concatenation, Split, Repeat, Tile.
* Other advanced concepts such as broadcasting describes how arithmetic works between arrays of different shap